### PR TITLE
Tag feature implemented as patch to plugin

### PR DESCRIPTION
**Pull request by HachiDD12**
Edited plugin source file autofill.js to add in new functionality on tagging posts
Should link posts when input matches the format $pid where pid is id of post in database
Progress towards issue #13, tag range checking is still TODO

### CODE REVIEW

**Review by Quarks-1 — CHANGES_REQUESTED** [review]
It seems like the tagging functionality does not work yet, see image below
image
Tagging functionality also does not appear to display in the markdown preview while writing a post/reply, could be source for further investigation

**Comment by HachiDD12** [comment]
Switch to another logic s.t. when $num is matched, show suggestion for replacing the tag with link to /post/num, where the format autocomplete when user selects that suggestion. Now using # instead of $ in the replaced text for purpose of avoiding string format related bugs.

**Review by Quarks-1 — APPROVED** [review]
All changes look good to me! Tested this branch locally and it works as expected.  It is also passing the test suite, good work!

**Comment by HachiDD12** [comment]
Also closes #10

**Pull request merged**
